import type { AlertRule, AlertEvent } from '@/lib/types';

export const mockAlertRules: AlertRule[] = [
  {
    id: 'rule-1',
    farmId: 'farm-1',
    farmName: 'Green Valley Ranch',
    metric: 'Temperature',
    operator: '>',
    threshold: 35,
    severity: 'high',
    enabled: true,
    createdAt: '2024-10-01T08:00:00Z',
  },
  {
    id: 'rule-2',
    farmId: 'farm-3',
    farmName: 'Rift View Farm',
    metric: 'Health Score',
    operator: '<',
    threshold: 50,
    severity: 'critical',
    enabled: true,
    createdAt: '2024-11-15T09:00:00Z',
  },
  {
    id: 'rule-3',
    farmId: 'farm-2',
    farmName: 'Sunrise Acres',
    metric: 'Rain Probability',
    operator: '>',
    threshold: 70,
    severity: 'medium',
    enabled: true,
    createdAt: '2025-02-10T10:00:00Z',
  },
  {
    id: 'rule-4',
    farmId: 'farm-7',
    farmName: 'Cedar Creek Farm',
    metric: 'Humidity',
    operator: '<',
    threshold: 30,
    severity: 'low',
    enabled: false,
    createdAt: '2025-06-20T14:00:00Z',
  },
];

export const mockAlertEvents: AlertEvent[] = [
  {
    id: 'evt-1',
    ruleId: 'rule-2',
    farmId: 'farm-3',
    farmName: 'Rift View Farm',
    metric: 'Health Score',
    value: 45,
    threshold: 50,
    severity: 'critical',
    status: 'active',
    triggeredAt: '2026-06-03T14:30:00Z',
  },
  {
    id: 'evt-2',
    ruleId: 'rule-1',
    farmId: 'farm-1',
    farmName: 'Green Valley Ranch',
    metric: 'Temperature',
    value: 37,
    threshold: 35,
    severity: 'high',
    status: 'acknowledged',
    triggeredAt: '2026-06-02T12:00:00Z',
  },
  {
    id: 'evt-3',
    ruleId: 'rule-3',
    farmId: 'farm-2',
    farmName: 'Sunrise Acres',
    metric: 'Rain Probability',
    value: 85,
    threshold: 70,
    severity: 'medium',
    status: 'resolved',
    triggeredAt: '2026-05-30T09:00:00Z',
  },
  {
    id: 'evt-4',
    ruleId: 'rule-2',
    farmId: 'farm-3',
    farmName: 'Rift View Farm',
    metric: 'Health Score',
    value: 42,
    threshold: 50,
    severity: 'critical',
    status: 'active',
    triggeredAt: '2026-05-28T16:00:00Z',
  },
  {
    id: 'evt-5',
    ruleId: 'rule-1',
    farmId: 'farm-1',
    farmName: 'Green Valley Ranch',
    metric: 'Temperature',
    value: 36,
    threshold: 35,
    severity: 'high',
    status: 'resolved',
    triggeredAt: '2026-05-25T11:00:00Z',
  },
];
